<!--[if IE 8]>
<script type="text/javascript" src="/statics/js/squire/build/ie8.js"></script>
<![endif]-->
<link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<link href="/statics/js/squire/build/Squire-UI.css" rel="stylesheet" type="text/css" />
<script src="/statics/js/squire/build/jQuery/jQuery.js" type="text/javascript"></script>
<script src="/statics/js/squire/build/squire-raw.js" type="text/javascript"></script>
<script src="/statics/js/squire/build/Squire-UI.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        window.editor = new SquireUI({
                replace: 'textarea#editor',
                height: Math.max($(document).height() - 300, 300),
                buildPath: "/statics/js/squire/build/"
        });
        window.editor
                .setTextDirection('auto')
                .setFontSize('16px');
        var init_draft = function() {
            if(localStorage.getItem("note-draft") === null)
                 localStorage["note-draft"] = JSON.stringify({}); 
        };
        var draft_exists = function() {
            return get_draft() !== undefined;
        };
        var discard_draft = function() {
            var hash = JSON.parse(localStorage["note-draft"]);
            delete hash["new"];
            localStorage["note-draft"] = JSON.stringify(hash);
        };
        var set_draft = function(d) {
            var hash = JSON.parse(localStorage["note-draft"]);
            hash["new"] = d;
            localStorage["note-draft"] = JSON.stringify(hash);
        };
        var get_draft = function() {
            var hash = JSON.parse(localStorage["note-draft"]);
            return hash["new"];
        };
        $("form[name='editor-form']").submit(function(){
            clearInterval(draft_int);
            $(this).append("<input type='hidden' name='content'>");
            $(this).find("[name='content']").val(window.editor.getHTML());
            discard_draft();
            return true;
        });
        $("#draft-notation").hide();
        init_draft();
        if(draft_exists()) {
                var draft = get_draft();
                $("[name='title']").val(draft.title);
                window.editor.setHTML(draft.body);
        }
        var previous_draft = { title: $("[name='title']").val(), body: window.editor.getHTML() };
        var draft_int = setInterval(function() {
            var current_draft = { title: $("[name='title']").val(), body: window.editor.getHTML() };
            if(current_draft.title === previous_draft.title && current_draft.body === previous_draft.body) return;
            set_draft(current_draft);
            previous_draft = current_draft;
            $("#draft-notation").fadeIn().delay(3000).fadeOut();
        }, 10000);
        $("#discard-draft").click(function() {
            if(localStorage.getItem("note-draft") !== null) {
                if(confirm("Are you sure that you want to drop the saved draft?")) {
                    clearInterval(draft_int);
                    discard_draft();
                    window.location.href = "/";
                }
            } else window.location.href = "/";
        });
    });
</script>
<style>
    .btn {background-color:#fff!important; font-weight: bold; color:#000;border-radius: 0;margin-top: 0px;}
</style>
<div class="container">
    <div class="row">
        <form action="<?php $this->request->getURI(); ?>?<?php echo \zinux\kernel\security\security::__get_uri_hash_string() ?>" method="post" name="editor-form">
            <div class="col-centered">
                <div class="container-fluid" style="padding: 5px 0 5px 0; padding-left: 0;">
                    <input type="text" class="form-control pull-left" style="border-radius: 0; min-width: 300px; width: 70%;" placeholder="Some heroic disqusion title!" required autofocus name="title" />
                    <a href='#' data-href='/' id="discard-draft" class='btn btn-default pull-right' tabindex="-1"><span class='fa fa-trash'></span> Discard</a>
                    <div class="pull-right text-muted btn" id="draft-notation" style="font-weight: initial; color:#aaa"><span class="fa fa-check draft-notation-icon"></span> <span id="draft-notation-text">draft saved</span></div>
                    <div class="clearfix"></div>
                </div>
                <textarea id="editor"></textarea>
            </div>
            <div class="col-centered">
            <button type="submit" class='btn btn-default pull-right' style='background-color:#fff!important; font-weight: bold; color:#000;border-radius: 0'><span class='fa fa-save'></span> Save</button>
            </div>
        </form>
    </div>
</div>