<!--[if IE 8]>
<script type="text/javascript" src="/statics/js/Squire/build/ie8.js"></script>
<![endif]-->
<link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<link href="/statics/js/Squire/build/Squire-UI.css" rel="stylesheet" type="text/css" />
<link href="/statics/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="/statics/js/Squire/build/jQuery/jQuery.js" type="text/javascript"></script>
<script src="/statics/js/Squire/build/squire-raw.js" type="text/javascript"></script>
<script src="/statics/js/Squire/build/Squire-UI.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
$(document).ready(function () {
    new SquireUI({replace: 'textarea#foo', height: 400, buildPath: "/statics/js/Squire/build/"});
});
</script>
<div class="container">
    <div class="row">
        <div class="col-centered">
           <textarea id="foo"></textarea>
        </div>
    </div>
</div>