<?php if(!is_array(@$this->query)) throw new zinux\kernel\exceptions\invalidOperationException; ?>
<div>
    <header  style="border-bottom: 1px #e7e7e7 solid;padding-bottom: 15px">
        <h1 id="disqus-title"><small class="fa fa-angle-double-right"></small> <?= $this->disqus->title ?></h1>
        <div id='origin_author' class="author text-muted" style="font-size: small" >Created by <abbr style="border-bottom: 2px #aaa dotted"><?= $this->disqus->user()->username ?></abbr></div>
        <div class="clearfix"></div>
    </header>
    <div class='new-disqus' style='margin: 10px;'>
        <div class='pull-right'><a id='reply-disqus' href='#' onclick="return false;"><span class='fa fa-reply'></span> Disqus</a></div>
        <div class='pull-left' id='reply-editor' style='display: none'><?php // $this->RenderPartial('new', array('parentid' => $this->disqus->disqusid, 'request_uri' => '/disqus/new')) ?></div>
        <div class='clearfix'></div>
    </div>
    <?php foreach ($this->query as $disqus) : ?>
    <div class='idisqus ' style="border:1px solid #eee; padding: 10px; margin: 10px">
        <div class="" style="">
        <?= $disqus->context ?>
        </div>
        <div class='idisqus-footer' style='border-top: 1px solid #eee; padding: 10px; padding-bottom: 0; margin-top: 10px'>
            <div class="author text-muted pull-left" style='font-size: small'>
                Posted by <?= $disqus->user()->username ?> <span class='fa fa-clock-o'></span>
                Created <abbr class='time' data-date='<?= $disqus->created_at ?>'></abbr>
                <?= date_diff($disqus->created_at, $disqus->updated_at)->format('%h') /* no edition within an hour will be counted */ ? " | Edited <abbr class='time' data-date='{$disqus->updated_at}'></abbr>" : "" ?>
            </div>
            <?php if($disqus->created_by == \modules\defaultModule\models\user::GetInstance()->userid) : ?>
            <div class='pull-right'>
                <ul class='list-inline' style='margin: 0'>
                    <li >
                        <a class='delete-it text-muted' href='#' data-href='/disqus/delete/<?= $disqus->disqusid, "?", \zinux\kernel\security\security::__get_uri_hash_string(array($disqus->disqusid)) ?>'>
                            <span class='fa fa-trash'></span> Delete
                        </a>
                    </li>
                    <li>
                        <a class='edit-it' href='/disqus/edit/<?= $disqus->disqusid, "?", \zinux\kernel\security\security::__get_uri_hash_string(array($disqus->disqusid)) ?>'>
                            <span class='fa fa-pencil'></span> Edit
                        </a>
                    </li>
                </ul>
            </div>
            <?php endif; ?>
            <div class='clearfix'></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php endforeach; ?>
</div>
<?php $margin = 3; if($this->total_pages > 1) : ?>
<nav class="text-center">
  <ul class="pagination">
    <li>
      <a href="/disqus/view/<?= $this->disqus->disqusid ?>/~/page/<?=  max($this->current_page - 1, 1); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <?php if(max($this->current_page - $margin, 1) != 1) : ?>
    <li><a href="/disqus/view/<?= $this->disqus->disqusid ?>/~/page/1">1</a></li>
    <li><a>...</a></li>
    <?php endif; ?>
    <?php for($i = max($this->current_page - $margin, 1); $i <= min($this->current_page + $margin, $this->total_pages); $i++) : ?>
    <li class="<?= $i == $this->current_page ? "active" : "" ?>"><a href="/disqus/view/<?= $this->disqus->disqusid ?>/~/page/<?= $i ?>"><?= $i ?></a></li>
    <?php endfor; ?>
    <?php if(min($this->current_page + $margin, $this->total_pages) != $this->total_pages) : ?>
    <li><a>...</a></li>
    <li><a href="/disqus/view/<?= $this->disqus->disqusid ?>/~/page/<?= $this->total_pages ?>"><?= $this->total_pages ?></a></li>
    <?php endif; ?>
    <li>
      <a href="/disqus/view/<?= $this->disqus->disqusid ?>/~/page/<?= min($this->current_page + 1, $this->total_pages) ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
<?php endif; ?>
<script type="text/javascript" src="/statics/js/moment.min.js"></script>
<script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
<script type='text/javascript'>
    $(document).ready(function(){
        $("abbr.time").each(function() {
            $(this).text(moment($(this).attr('data-date')).fromNow('ll') + " ago");
            $(this).attr('title', moment($(this).attr('data-date')).format('lll'));
        });
        var replay_mutex = false;
        $("#reply-disqus").click(function() {
            if(replay_mutex) { return; }
            replay_mutex = true;
            $(this).hide();
            $('#reply-editor').show().html('<span class="fa fa-spin fa-spinner"></span>');
            $('#reply-editor').hide().load('/disqus/new?ajax=1&pid=<?= $this->disqus->disqusid?>', function() { replay_mutex = false; }).ready(function(){ $('#reply-editor').show(); });
        });
        $('.delete-it').click(function(e){
            e.preventDefault();
            $(this).closest('.idisqus').css({"background-color": "#F4EAEA"});
            if(confirm("Are you sure that you want to delete highlighted disqus?")) {
                var $elem = $(this);
                window.location = $elem.attr('data-href');
            } else {
                    $(this).closest('.idisqus').css({"background-color": "transparent"});
            }
        });
    });
</script>