<?php if(!isset($this->tags)) throw new RuntimeException("The tags manifest has not been provided!"); ?>
<?php if(isset($this->msg) && count($this->msg)): ?>
    <?php foreach ($this->msg as $msg) : ?>
    <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class='fa fa-quote-left pull-left' style='margin-top: -5px'></span> <strong>Update:</strong> <?= $msg ?>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
<fieldset style="margin: 20px;">
    <legend>Manage Tags</legend>
    <div class="row "style="padding:0 20px">
        <div class="col-md-4 col-xs-12 col-sm-3">
        <?php if(count($this->tags)): ?>
        <div class="dropdown" style="display: inline">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class='fa fa-tags'></span> Select Tag
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" id="selectArea">
                <?php foreach($this->tags as $tag): ?>
                <li class="tag"><a href="#" href-data="<?= $tag->tag_id; ?>" onclick="return false;"><span class='fa fa-tag'></span> <?= $tag->tag_name; ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div> <div class="text-muted" style="display: inline">or</div>
        <?php endif; ?>
        <a href="#" onclick="return false;" id="newArea"><span class="fa fa-plus"></span> Create new</a>.
        </div>
        <div class="col-md-8 col-xs-12 col-sm-9" id="editArea">
            <form action="/tags/update?<?= \zinux\kernel\security\security::__get_uri_hash_string(); ?>" method="POST">
            <div class="input-group pull-left">
                <input type="text" class="form-control" name="tag_name" required>
                <div class="input-group-btn">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></button>
                  <ul class="dropdown-menu dropdown-menu-right">
                      <li id="update-create"><button type="submit" class="btn btn-link" name="op:update"><span class="fa fa-pencil"></span> Update/Create</button></li>
                    <li role="separator" class="divider"></li>
                    <li id="delete"><button type="submit" class="btn btn-link" name="op:delete" onclick="return confirm('Are you sure you want to delete this tag?\nThis will delete all post under this category and it\'s irreversible!!');"><span class="fa fa-trash"></span> Delete</button></li>
                  </ul>
                </div>
            </div>
        </form>
        </div>
    </div>
</fieldset>
<script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
<script type="text/javascript">
    var disableEditArea = function(flag) { $("#editArea *").attr("disabled", flag); };
    $(document).ready(function(){
        disableEditArea(true);
        $("#editArea form input[name='tag_name']").val('');
        $("#selectArea .tag a").click(function(){
            var id = $(this).attr('href-data');
            $("#editArea form").append("<input type='hidden' name='tag_id' value='"+id+"' />");
            $("#editArea form input[name='tag_name']").val($(this).text()).focus();
            disableEditArea(false);
        });
        $("a#newArea").click(function(){
            disableEditArea(false);
            $('#editArea #delete button').attr('disabled', true);
            $("#editArea form input[name='tag_id']").remove();
            $("#editArea form input[name='tag_name']").val('').focus();
        });
    });
</script>
<style type="text/css">
    #editArea button[type=submit].btn-link { color: black; margin:0 }
</style>