<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <?php $this->RenderTitle();?>
    <?php $this->RenderImports(); ?>
    <!-- Bootstrap Core CSS -->
    <link href="/statics/css/bootstrap.min.css" rel="stylesheet">
    <link href="/statics/css/font-awesome.min.css" rel="stylesheet" >
    <link href="/statics/css/scrolling-nav.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body data-spy="scroll" data-target=".navbar-fixed-top" id="page-top">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/"><span class="fa fa-database"></span> iDisqus</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                    <?php if(!\modules\defaultModule\models\user::HasSignedin()): ?>
                        <a class="page-scroll" href="/signin"><span class="fa fa-sign-in"></span> Signin</a>
                    <?php else: ?>
                        <a class="page-scroll" href="/signout"><span class="fa fa-sign-out"></span> Signout</a>
                    <?php endif; ?>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
            <?php if(\modules\defaultModule\models\user::HasSignedin()): ?>
            <div class="collapse navbar-collapse navbar-ex1-collapse pull-left">
                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <a href="/disqus/new"><span class="fa fa-plus"></span> Disqus</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
            <?php endif; ?>
        </div><!-- /.container -->
    </nav>
    <div class="container" style="padding-top: 100px;">
        <?php echo $this->content; ?>
    </div>
    <script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
    <script src="/statics/js/bootstrap.min.js" type="text/javascript"></script> 
    <script src="/statics/js/jquery.easing.min.js" type="text/javascript"></script> 
    <script src="/statics/js/scrolling-nav.min.js" type="text/javascript"></script>
</body>
</html>