<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <?php $this->RenderTitle();?>
    <?php $this->RenderImports(); ?>
    <!-- Bootstrap Core CSS -->
    <link href="/statics/css/bootstrap.min.css" rel="stylesheet">
    <link href="/statics/css/font-awesome.min.css" rel="stylesheet" >
    <link href="/statics/css/scrolling-nav.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body data-spy="scroll" data-target=".navbar-fixed-top" id="page-top">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/"><span class="fa fa-database"></span> iDisqus</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <?php if(!\modules\defaultModule\models\user::HasSignedin()): ?>
                    <li>
                        <a class="page-scroll" href="/signup"><span class="fa fa-plug"></span> Signup</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/signin"><span class="fa fa-sign-in"></span> Signin</a>
                    </li>
                    <?php else: ?>
                    <li>
                        <a class="page-scroll" href="/signout"><span class="fa fa-sign-out"></span> Signout</a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div><!-- /.navbar-collapse -->
            <div class="collapse navbar-collapse navbar-ex1-collapse pull-left">
                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
            	<?php if(\modules\defaultModule\models\user::HasSignedin()): ?>
                    <li>
                        <a href="/disqus/new<?= isset($this->request->params["tag"]) ? "/tag/{$this->request->params["tag"]}" : ""; ?>"><span class="fa fa-plus"></span> Disqus<?= isset($this->request->params["tag"]) ? " : {$this->request->params["tag"]}" : ""; ?></a>
                    </li>
            	<?php endif; ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-code-fork"></span> Topics<?= isset($this->request->params["tag"]) ? " : {$this->request->params["tag"]}" : "" ?><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <?php $tags =\modules\defaultModule\models\tag::make_list(); ?>
                            <?php foreach ($tags as $tag) : ?>
                            <li <?php echo @$this->request->params["tag"] == $tag->tag_name ? "style='background-color: #e8e8e8'": ""?>><a href='/tag/<?= $tag->tag_name; ?>'><span class="fa fa-file-code-o"></span> <?= ucwords($tag->tag_name) ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <li>
                        <a href="/about"><span class="fa fa-info-circle"></span> About us</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
    <div class="container" style="padding-top: 100px;">
        <?php echo $this->content; ?>
    </div>
    <script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
    <script src="/statics/js/bootstrap.min.js" type="text/javascript"></script> 
    <script src="/statics/js/jquery.easing.min.js" type="text/javascript"></script> 
    <script src="/statics/js/scrolling-nav.min.js" type="text/javascript"></script>
</body>
</html>