<?php if(!isset($this->total_pages) || !isset($this->query)) throw new \zinux\kernel\exceptions\invalidArgumentException; ?>
<?php
function truncate($text, $length = 100, $ending = '...', $exact = true, $considerHtml = true) {
    if (is_array($ending)) {
        extract($ending);
    }
    if ($considerHtml) {
        if (mb_strlen(preg_replace('/<.*?>/', '', $text)) <= $length) {
            return $text;
        }
        $totalLength = mb_strlen($ending);
        $openTags = array();
        $truncate = '';
        preg_match_all('/(<\/?([\w+]+)[^>]*>)?([^<>]*)/', $text, $tags, PREG_SET_ORDER);
        foreach ($tags as $tag) {
            if (!preg_match('/img|br|input|hr|area|base|basefont|col|frame|isindex|link|meta|param/s', $tag[2])) {
                if (preg_match('/<[\w]+[^>]*>/s', $tag[0])) {
                    array_unshift($openTags, $tag[2]);
                } else if (preg_match('/<\/([\w]+)[^>]*>/s', $tag[0], $closeTag)) {
                    $pos = array_search($closeTag[1], $openTags);
                    if ($pos !== false) {
                        array_splice($openTags, $pos, 1);
                    }
                }
            }
            $truncate .= $tag[1];

            $contentLength = mb_strlen(preg_replace('/&[0-9a-z]{2,8};|&#[0-9]{1,7};|&#x[0-9a-f]{1,6};/i', ' ', $tag[3]));
            if ($contentLength + $totalLength > $length) {
                $left = $length - $totalLength;
                $entitiesLength = 0;
                if (preg_match_all('/&[0-9a-z]{2,8};|&#[0-9]{1,7};|&#x[0-9a-f]{1,6};/i', $tag[3], $entities, PREG_OFFSET_CAPTURE)) {
                    foreach ($entities[0] as $entity) {
                        if ($entity[1] + 1 - $entitiesLength <= $left) {
                            $left--;
                            $entitiesLength += mb_strlen($entity[0]);
                        } else {
                            break;
                        }
                    }
                }

                $truncate .= mb_substr($tag[3], 0 , $left + $entitiesLength);
                break;
            } else {
                $truncate .= $tag[3];
                $totalLength += $contentLength;
            }
            if ($totalLength >= $length) {
                break;
            }
        }

    } else {
        if (mb_strlen($text) <= $length) {
            return $text;
        } else {
            $truncate = mb_substr($text, 0, $length - strlen($ending));
        }
    }
    if (!$exact) {
        $spacepos = mb_strrpos($truncate, ' ');
        if (isset($spacepos)) {
            if ($considerHtml) {
                $bits = mb_substr($truncate, $spacepos);
                preg_match_all('/<\/([a-z]+)>/', $bits, $droppedTags, PREG_SET_ORDER);
                if (!empty($droppedTags)) {
                    foreach ($droppedTags as $closingTag) {
                        if (!in_array($closingTag[1], $openTags)) {
                            array_unshift($openTags, $closingTag[1]);
                        }
                    }
                }
            }
            $truncate = mb_substr($truncate, 0, $spacepos);
        }
    }

    $truncate .= $ending;

    if ($considerHtml) {
        foreach ($openTags as $tag) {
            $truncate .= '</'.$tag.'>';
        }
    }

    return $truncate;
}?>
<div style="margin-top: 30px;"></div>
 <?php foreach($this->query as $index => $disqus) : ?>
<disqus id="disqus-<?= $index ?>">
    <div style="border-bottom: 1px solid #eee">
        <h3 style="margin: 0"><small class="fa fa-angle-double-right"></small> <a href="/disqus/view/<?= $disqus->disqusid ?>"><?= $disqus->title ?></a></h3>
        <small class="text-muted">
            <span class="pull-right" style="margin:3px; margin-top: 10px">by <?= $disqus->username ?></span>
            <span class="updated-date pull-right" style="margin:3px; margin-top: 10px" data-date='<?= $disqus->updated_at ?>'></span>
            <span class="fa fa-pencil pull-right" style='margin:3px; margin-top: 10px'></span> 
        </small>
        <div class="clearfix"></div>
    </div>
    <div style="margin: 10px;" >
        <span class="pull-left text-justify"><?= truncate($disqus->context, 200) ?></span>
    </div>
    <div class="clearfix" style="margin-top: 70px!important;"></div>
</disqus>
<?php endforeach; ?>
<?php $margin = 3; if($this->total_pages > 1) : ?>
<nav class="text-center">
  <ul class="pagination">
    <li>
      <a href="/page/<?=  max($this->current_page - 1, 1); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <?php if(max($this->current_page - $margin, 1) != 1) : ?>
    <li><a href="/page/1">1</a></li>
    <li><a>...</a></li>
    <?php endif; ?>
    <?php for($i = max($this->current_page - $margin, 1); $i <= min($this->current_page + $margin, $this->total_pages); $i++) : ?>
    <li class="<?= $i == $this->current_page ? "active" : "" ?>"><a href="/page/<?= $i ?>"><?= $i ?></a></li>
    <?php endfor; ?>
    <?php if(min($this->current_page + $margin, $this->total_pages) != $this->total_pages) : ?>
    <li><a>...</a></li>
    <li><a href="/page/<?= $this->total_pages ?>"><?= $this->total_pages ?></a></li>
    <?php endif; ?>
    <li>
      <a href="/page/<?= min($this->current_page + 1, $this->total_pages) ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
<?php endif; ?>
<script type="text/javascript" src="/statics/js/moment.min.js"></script>
<script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
<script type='text/javascript'>
    $(document).ready(function(){
        $(".updated-date[data-date]").each(function(index, elem) {
            $(this).text("Last update: " + moment($(this).attr('data-date')).fromNow('ll') + " ago;");
        });
    });
</script>
