<?php if(!isset($this->total_pages) || !isset($this->query)) throw new \zinux\kernel\exceptions\invalidArgumentException; ?>
<div style="margin-top: 30px;"></div>
 <?php foreach($this->query as $index => $disqus) : ?>
<div id="disqus-<?= $index ?>" style='margin: 10px; padding: 10px;'>
    <div style="border-bottom: 1px solid #eee">
        <h3 style="margin: 0"  dir="auto"><small class="fa fa-thumb-tack"></small> <a href="/disqus/view/<?= $disqus->disqusid ?>"><?= $disqus->title ?></a></h3>
        <?php if(@$disqus->tag_id): ?>
        <ol class="list-inline pull-left" style='margin:3px; margin-top: 10px'>
            <?php $tag = \modules\defaultModule\models\tag::find(@$disqus->tag_id)->tag_name; ?>
            <li class='active'><span class='fa fa-tag'></span> <a href='/tag/<?= $tag ?>'><?= $tag ?></a>
        </ol>
        <?php endif; ?>
        <small class="text-muted">
            <span class="updated-date pull-right" style="margin:3px; margin-top: 10px" data-date='<?= $disqus->updated_at ?>'></span>
            <span class="pull-right" style="margin:3px; margin-top: 10px">By <span style="border-bottom: 2px dotted #aaa"><?= $disqus->username ?></span></span>
            <span class="fa fa-pencil pull-right" style='margin:0px; margin-top: 12px'></span> 
        </small>
        <div class="clearfix"></div>
    </div>
    <div style="margin: 10px; display: none" dir="auto" class="disqus-content">
        <?= substr(/*strip_tags*/($disqus->context), 0) ?>
    </div>
    <div class='text-center disqus-content-spinner' style="font-size: 170%"><span class='fa fa-spinner fa-spin'></span></div>
    <div class="clearfix" style="margin-top: 70px!important;"></div>
</div>
<?php endforeach; ?>
<?php if(!count($this->query)): ?>
<div style='border: 1px solid #eee; padding: 20px;' class='text-muted text-center'>
    Woow, No Disqus!!
    <?php if(\modules\defaultModule\models\user::HasSignedin()) : ?>
    <br />You can always <a href='/disqus/new<?= isset($this->request->params["tag"]) ? "/tag/{$this->request->params["tag"]}" : "" ?>'>create</a> new disquses.
    <?php endif; ?>
</div>
<?php endif; ?>
<?php $margin = 3; if($this->total_pages > 1) : ?>
<nav class="text-center">
  <ul class="pagination">
    <li>
      <a href="/page/<?=  max($this->current_page - 1, 1); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <?php if(max($this->current_page - $margin, 1) != 1) : ?>
    <li><a href="/page/1">1</a></li>
    <li><a>...</a></li>
    <?php endif; ?>
    <?php for($i = max($this->current_page - $margin, 1); $i <= min($this->current_page + $margin, $this->total_pages); $i++) : ?>
    <li class="<?= $i == $this->current_page ? "active" : "" ?>"><a href="/page/<?= $i ?>"><?= $i ?></a></li>
    <?php endfor; ?>
    <?php if(min($this->current_page + $margin, $this->total_pages) != $this->total_pages) : ?>
    <li><a>...</a></li>
    <li><a href="/page/<?= $this->total_pages ?>"><?= $this->total_pages ?></a></li>
    <?php endif; ?>
    <li>
      <a href="/page/<?= min($this->current_page + 1, $this->total_pages) ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
<?php endif; ?>
<script type="text/javascript" src="/statics/js/moment.min.js"></script>
<script type="text/javascript" src="/statics/js/jquery.min.js"></script> 
<script type='text/javascript'>
    $(document).ready(function(){
        $(".updated-date[data-date]").each(function(index, elem) {
            $(this).html("<span class='fa fa-clock-o'></span> " + moment($(this).attr('data-date')).fromNow('ll') + " ago");
        });
        $(".disqus-content").each(function(){
            var s = 2000;
            var wc = $(this).text().split(" ").length;
            var hc = 200;
            if(wc < 100) { $(this).show().next('.disqus-content-spinner').remove(); return; }
            var show_more_text = '<strong><i class="fa fa-caret-down"></i> Show More!</strong>';
            var show_less_text = '<strong><i class="fa fa-caret-up"></i> Show Less!</strong>';
            $('<div class="text-expand text-center">'+show_more_text+'</div>').hide().insertAfter(this).fadeIn(s).data('origin-height', $(this).height()).data('origin-elem', this).click(function(){
                var origin_elem = $(this).data('origin-elem');
                console.log([$(origin_elem).height() , $(this).data('origin-height')]);
                if($(origin_elem).innerHeight() !== $(this).data('origin-height')) {
                    $(origin_elem).animate({height: $(this).data('origin-height')});
                    $(this).html(show_less_text);
                } else {
                    $(origin_elem).animate({height: hc});
                    $(this).html(show_more_text);
                }
            });
            $(this).fadeIn(s).height(hc);
            $(this).parent().find('.disqus-content-spinner').remove();
        });
    });
</script>
<style type='text/css'>.text-expand{border:1px solid #e7e7e7;color:#ADADAD;padding:10px;margin-top:0;cursor:pointer}.disqus-content{overflow-y:hidden}</style>
