<style>.form-signup{max-width:500px;padding:15px;margin:0 auto}.form-signup .form-signup-heading{border-bottom:1px solid #ccc;margin:-15px -15px 30px;padding:10px}.form-signup .checkbox{margin:15px auto;font-weight:400}.form-signup .form-control{position:relative;height:auto;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:10px;font-size:16px}.form-signup .form-control:focus{z-index:2}.form-signup input[type=email]{margin-bottom:-1px;border-bottom-right-radius:0;border-bottom-left-radius:0}.form-signup input[type=password]{margin-bottom:10px;border-top-left-radius:0;border-top-right-radius:0}</style>
<div class='container'>
    <form class="form-signup" action="/signup?<?php echo \zinux\kernel\security\security::__get_uri_hash_string(); ?>" method="post">
        <h2 class="form-signup-heading"><span class='fa fa-plug'></span> Sign up</h2>
        <?php if(@count($this->errors)) : ?>
        <ul class="list-unstyled" style="margin-bottom: 20px">
            <?php foreach ($this->errors as $error) : ?>
            <li style="color:red"><span class="fa fa-exclamation-triangle"></span> <?php echo $error ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <?php if(@count($this->success)) : ?>
        <ul class="list-unstyled" style="margin-bottom: 20px">
            <?php foreach ($this->success as $success) : ?>
            <li class="text-success"><span class="fa fa-check"></span> <?php echo $success ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <label for="inputUsername" class="sr-only">Username</label>
        <input id="inputUsername" class="form-control" placeholder="Username" required autofocus tabindex="1" name="username">
        <label for="inputEmail" class="sr-only">Email address</label>
        <input id="inputEmail" class="form-control" placeholder="Email" required autofocus tabindex="2" name="email" type="email">
        <label for="inputPassword1" class="sr-only">Password</label>
        <input id="inputPassword1" class="form-control" placeholder="password" required autofocus tabindex="3" name="password" type="password">
        <label for="inputPassword2" class="sr-only">Re-type Password</label>
        <input id="inputPassword2" class="form-control" placeholder="Re-type Password" required tabindex="4"  type="password">
        <button class="btn btn-lg btn-primary btn-block" type="submit" tabindex="6">Sign up</button>
    </form>
</div>
<script src="/statics/js/jquery.min.js" type="text/javascript"></script> 
<script type="text/javascript">
    $(document).ready(function(){
        $("form.form-signup").submit(function(){
            var ok_pass = $("#inputPassword1[type='password']").val() === $("#inputPassword2[type='password']").val()
            if(!ok_pass)
                $("[type='password']").css('border', '1px solid #D9534F');
            return ok_pass;
        });
    });
</script>