<style>.form-signin{max-width:400px;padding:15px;margin:0 auto}.form-signin .form-signin-heading{border-bottom:1px solid #ccc;margin:-15px -15px 30px;padding:10px}.form-signin .checkbox{margin:15px auto;font-weight:400}.form-signin .form-control{position:relative;height:auto;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:10px;font-size:16px}.form-signin .form-control:focus{z-index:2}.form-signin input[type=email]{margin-bottom:-1px;border-bottom-right-radius:0;border-bottom-left-radius:0}.form-signin input[type=password]{margin-bottom:10px;border-top-left-radius:0;border-top-right-radius:0}</style>
<div class='container'>
    <form class="form-signin" action="/signin?<?php echo \zinux\kernel\security\security::__get_uri_hash_string(); ?>" method="post">
        <h2 class="form-signin-heading"><span class='fa fa-sign-in'></span> Sign in</h2>
        <?php if(@count($this->errors)) : ?>
        <ul class="list-unstyled" style="margin-bottom: 20px">
            <?php foreach ($this->errors as $error) : ?>
            <li style="color:red"><span class="fa fa-exclamation-triangle"></span> <?php echo $error ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <label for="inputEmail" class="sr-only">Email address or Username</label>
        <input id="inputEmail" class="form-control" placeholder="Username or Email" required autofocus tabindex="1" name="username">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required tabindex="2" name="password">
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me" checked tabindex="4" name="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" tabindex="3">Sign in</button>
    </form>
</div>